language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.2

before_install:
  - gem install ruby-debug-ide
  - nvm install 8.9.3
  - echo "8.9.3" > .nvmrc

before_script:
  - nvm use
  - npm install -g typescript -v 2.1.5
  - npm install
  - npm run compile
script: nvm use && npm run test-debugger
